### ISSUE TITLE
Выдает ошибку при работе bsl.languageserver

### ISSUE THREAD

**Issue by arXXXimed** [1c-syntax/vsc-language-1c-bsl#187]
При попытке редактировать или ввести текст 1С выдает ошибку
```
`����. 14, 2020 2:04:38 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(Unknown Source)
	at com.github._1c_syntax.bsl.languageserver.utils.Absolute.path(Absolute.java:48)
	at com.github._1c_syntax.bsl.languageserver.utils.Absolute.uri(Absolute.java:38)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:61)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:56)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.codeAction(BSLTextDocumentService.java:159)
	... 16 more

[Error - 14:04:38] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more

Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(Unknown Source)
	at com.github._1c_syntax.bsl.languageserver.utils.Absolute.path(Absolute.java:48)
	at com.github._1c_syntax.bsl.languageserver.utils.Absolute.uri(Absolute.java:38)

	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:61)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:56)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.codeAction(BSLTextDocumentService.java:159)
	... 16 more
```

**Comment by nixel2007** [comment]
Добрый день. Редактируете файл по сети?

**Comment by arXXXimed** [comment]
Нет. я просто давно не запускал VSCode. Сейчас когда запустил постоянно выскакивают ошибки такого типа. Редактирую не сохраненный файл. То есть просто в новый файл вставляю текст и выбираю тип текста BSL. Пробовал переустановить JAVA. Удалял VScode переустанавливал раширение

**Comment by nixel2007** [comment]
Поддержка работы с несохраненными файлами будет в следующем релизе бсл лс. Пока просто сохраните файл.
