### ISSUE TITLE
Ошибка инициализации

### ISSUE THREAD

**Issue by shalimski** [1c-syntax/vsc-language-1c-bsl#236]
Зависает инициализация, в логах следующая ошибка

`TypeError: Cannot read property 'uri' of undefined
	at LanguageClientProvider.<anonymous> (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:202:64)
	at Generator.next (<anonymous>)
	at c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:4:12)
	at LanguageClientProvider.getConfigurationFile (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:196:16)
	at LanguageClientProvider.<anonymous> (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:184:50)
	at Generator.next (<anonymous>)
	at c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:4:12)
	at LanguageClientProvider.getExecutableBinary (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:178:16)
	at LanguageClientProvider.<anonymous> (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:120:30)
	at Generator.next (<anonymous>)
	at c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:4:12)
	at LanguageClientProvider.createLanguageClient (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:115:16)
	at LanguageClientProvider.<anonymous> (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:95:47)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js:5:58)`

**Comment by nixel2007** [comment]
Добрый день.

Поменяйте строку 199 в файле c:\Users\Ivanov.II\.vscode\extensions\1c-syntax.language-1c-bsl-1.24.2\out\src\features\languageClientProvider.js на
```js
if (!workspaceFolders || workspaceFolders.length === 0) {
```
