### ISSUE TITLE
Не могу запустить BSL LS

### ISSUE THREAD

**Issue by nagaitseff** [1c-syntax/vsc-language-1c-bsl#259]
День добрый!
Никак не получается запустить BSL на компьютере. Подключаемся терминально к серверу, есть прокси организации. Соответственно все можно скопировать только в портативной версии, установка ПО запрещена.
**Помогите пожалуйста запустить!**

Ошибка: Client BSL Language Server: connection to server is erroring. Shutting down server.
The system cannot find the path specified.

И после 5 попыток следующее сообщение:
Error: Connection to server got closed. Server will not be restarted.
	at LanguageClient.handleConnectionClosed (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-languageclient\lib\common\client.js:2668:47)
	at LanguageClient.handleConnectionClosed (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-languageclient\lib\node\main.js:173:15)
	at closeHandler (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-languageclient\lib\common\client.js:2635:18)
	at CallbackList.invoke (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-jsonrpc\lib\common\connection.js:272:26)
	at CallbackList.invoke (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at StreamMessageReader.fireClose (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
	at Socket.<anonymous> (c:\Users\NagaytsevEP\.vscode\extensions\1c-syntax.language-1c-bsl-1.26.0\node_modules\vscode-jsonrpc\lib\common\messageReader.js:124:42)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)

**Comment by nixel2007** [comment]
Как устанавливали портативную версию и какую? Какие настройки прописали?

**Comment by nixel2007** [comment]
Хотя и прокси для node.js можно настроить

**Comment by nagaitseff** [comment]
> Как устанавливали портативную версию и какую? Какие настройки прописали?

1) Установил и обновил уже MS Code до версии: 
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.14393
Sandboxed: No

2) Language 1C (BSL) v1.26.0

3) Java 11 JDK Liberica 64 full

4) BSL Language - v0.20.0

Настройки:
{
    "workbench.colorTheme": "Default Dark+",
    "workbench.iconTheme": "material-icon-theme",
    "editor.unicodeHighlight.ambiguousCharacters": false,
    "git.autofetch": true,
    "window.commandCenter": true,
    "language-1c-bsl.downloadLanguageServer": true,
    "language-1c-bsl.rootPath": "C:\\REP\\ERP\\NAGAYTSEVEP\\CF",
    "language-1c-bsl.onescriptPath": "C:\\OneScript\\bin",
    "language-1c-bsl.languageServerExternalJarJavaPath": "C:\\jdk11\\bin\\java.exe",
    "security.workspace.trust.untrustedFiles": "open",
    "language-1c-bsl.languageServerExternalJar": false,
    "language-1c-bsl.languageServerBaseInstallDir": "C:\\bsl-language-server\\bsl-language-server.exe",
    "bsl.trace.server": "verbose",
    "editor.largeFileOptimizations": true,
    "language-1c-bsl.languageServerEnabled": true
}

**Comment by nagaitseff** [comment]
Экранирование с 2мя \ в путях

**Comment by nagaitseff** [comment]
> Хотя и прокси для node.js можно настроить

Как подскажите пожалуйста?

**Comment by nagaitseff** [comment]
Если ставлю галку на скачивание, то ошибка: Could not update/download BSL Language Server: Error: Could not fetch from GitHub releases API: RequestError: Error [ERR_SOCKET_CLOSED]: Socket is closed.
